-- MySQL Script generated by MySQL Workbench
-- Sun Nov 13 09:51:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Identificação` VARCHAR(45) NULL,
  `Pessoa Física` TINYINT NOT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veículos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veículos` (
  `idVeículos` INT NOT NULL,
  `Placa` INT NULL,
  `Modelo` VARCHAR(45) NULL,
  `Ano` YEAR(2) NULL,
  `Clientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idVeículos`, `Clientes_idClientes`),
  INDEX `fk_Veículos_Clientes_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Veículos_Clientes`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `mydb`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipes` (
  `idMão de Obra` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  PRIMARY KEY (`idMão de Obra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço` (
  `idOrdem de Serviço` INT NOT NULL,
  `Data de Emissão` DATETIME(10) NULL,
  `Tipo de OS` VARCHAR(45) NULL,
  `Valor Total` FLOAT(14,2) NULL,
  `Equipes_idMão de Obra` INT NOT NULL,
  `Prazo de entrega` INT NULL,
  `Conclusão` DATE NULL,
  `Status` VARCHAR(45) NULL,
  `Autorizado` TINYINT NULL,
  PRIMARY KEY (`idOrdem de Serviço`, `Equipes_idMão de Obra`),
  INDEX `fk_Ordem de Serviço_Equipes1_idx` (`Equipes_idMão de Obra` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_Equipes1`
    FOREIGN KEY (`Equipes_idMão de Obra`)
    REFERENCES `mydb`.`Equipes` (`idMão de Obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veículos designado a Equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veículos designado a Equipes` (
  `Veículos_idVeículos` INT NOT NULL,
  `Equipes_idMão de Obra` INT NOT NULL,
  PRIMARY KEY (`Veículos_idVeículos`, `Equipes_idMão de Obra`),
  INDEX `fk_Veículos_has_Equipes_Equipes1_idx` (`Equipes_idMão de Obra` ASC) VISIBLE,
  INDEX `fk_Veículos_has_Equipes_Veículos1_idx` (`Veículos_idVeículos` ASC) VISIBLE,
  CONSTRAINT `fk_Veículos_has_Equipes_Veículos1`
    FOREIGN KEY (`Veículos_idVeículos`)
    REFERENCES `mydb`.`Veículos` (`idVeículos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veículos_has_Equipes_Equipes1`
    FOREIGN KEY (`Equipes_idMão de Obra`)
    REFERENCES `mydb`.`Equipes` (`idMão de Obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mão de Obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mão de Obra` (
  `idMão de Obra` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Valor` FLOAT(10,2) NULL,
  PRIMARY KEY (`idMão de Obra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peças`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peças` (
  `idPeças` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Valor` FLOAT(10,2) NULL,
  PRIMARY KEY (`idPeças`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mão de Obra da Ordem de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mão de Obra da Ordem de Serviço` (
  `Mão de Obra_idMão de Obra` INT NOT NULL,
  `Ordem de Serviço_idOrdem de Serviço` INT NOT NULL,
  PRIMARY KEY (`Mão de Obra_idMão de Obra`, `Ordem de Serviço_idOrdem de Serviço`),
  INDEX `fk_Mão de Obra_has_Ordem de Serviço_Ordem de Serviço1_idx` (`Ordem de Serviço_idOrdem de Serviço` ASC) VISIBLE,
  INDEX `fk_Mão de Obra_has_Ordem de Serviço_Mão de Obra1_idx` (`Mão de Obra_idMão de Obra` ASC) VISIBLE,
  CONSTRAINT `fk_Mão de Obra_has_Ordem de Serviço_Mão de Obra1`
    FOREIGN KEY (`Mão de Obra_idMão de Obra`)
    REFERENCES `mydb`.`Mão de Obra` (`idMão de Obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mão de Obra_has_Ordem de Serviço_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_idOrdem de Serviço`)
    REFERENCES `mydb`.`Ordem de Serviço` (`idOrdem de Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peças da Ordem de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peças da Ordem de Serviço` (
  `Peças_idPeças` INT NOT NULL,
  `Ordem de Serviço_idOrdem de Serviço` INT NOT NULL,
  PRIMARY KEY (`Peças_idPeças`, `Ordem de Serviço_idOrdem de Serviço`),
  INDEX `fk_Peças_has_Ordem de Serviço_Ordem de Serviço1_idx` (`Ordem de Serviço_idOrdem de Serviço` ASC) VISIBLE,
  INDEX `fk_Peças_has_Ordem de Serviço_Peças1_idx` (`Peças_idPeças` ASC) VISIBLE,
  CONSTRAINT `fk_Peças_has_Ordem de Serviço_Peças1`
    FOREIGN KEY (`Peças_idPeças`)
    REFERENCES `mydb`.`Peças` (`idPeças`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peças_has_Ordem de Serviço_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_idOrdem de Serviço`)
    REFERENCES `mydb`.`Ordem de Serviço` (`idOrdem de Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecânico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecânico` (
  `idMecânico` INT NOT NULL,
  `Código` INT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Especialidade` VARCHAR(45) NULL,
  `Equipes_idMão de Obra` INT NOT NULL,
  PRIMARY KEY (`idMecânico`, `Equipes_idMão de Obra`),
  INDEX `fk_Mecânico_Equipes1_idx` (`Equipes_idMão de Obra` ASC) VISIBLE,
  CONSTRAINT `fk_Mecânico_Equipes1`
    FOREIGN KEY (`Equipes_idMão de Obra`)
    REFERENCES `mydb`.`Equipes` (`idMão de Obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
