-- MySQL Script generated by MySQL Workbench
-- Sun Nov  6 11:59:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedores` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `Razão Social` VARCHAR(255) NOT NULL,
  `Indentificação` CHAR(14) NOT NULL COMMENT 'Não sendo PessoaFísica TRUE então trata-se de CNPJ',
  `Contato` CHAR(11) NOT NULL,
  `PessoaFísica` TINYINT NOT NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`Indentificação` ASC) VISIBLE,
  UNIQUE INDEX `Razão Social_UNIQUE` (`Razão Social` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `Categoria` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Valor` FLOAT(14,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Indetificação` VARCHAR(14) NOT NULL,
  `PNome` VARCHAR(10) NOT NULL,
  `NmeioInicial` VARCHAR(3) NULL,
  `SobreNome` VARCHAR(20) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Pessoa Física` TINYINT NOT NULL,
  `Data de Nascimento` DATE NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `Indetificação_UNIQUE` (`Indetificação` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `idEntrega` INT NOT NULL AUTO_INCREMENT,
  `Endereço` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  `rastreio` VARCHAR(45) NULL,
  `Valor` FLOAT(10,2) NULL,
  `Data` DATE NULL,
  PRIMARY KEY (`idEntrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `Status do pedido` ENUM("Em Andamento", "Processando", "Enviado", "Entregue") NULL DEFAULT 'Processando',
  `Descrição` VARCHAR(45) NULL,
  `Clientes_idCliente` INT NOT NULL,
  `Frete` FLOAT(10,2) NOT NULL DEFAULT 0,
  `Entrega_idEntrega` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Clientes_idCliente`, `Entrega_idEntrega`),
  INDEX `fk_Pedidos_Clientes1_idx` (`Clientes_idCliente` ASC) VISIBLE,
  INDEX `fk_Pedidos_Entrega1_idx` (`Entrega_idEntrega` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `mydb`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Entrega1`
    FOREIGN KEY (`Entrega_idEntrega`)
    REFERENCES `mydb`.`Entrega` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Forma de Pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Forma de Pagamentos` (
  `idForma de Pagamento` INT NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NULL,
  PRIMARY KEY (`idForma de Pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disponibiliza Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disponibiliza Produtos` (
  `Fornecedores_idFornecedor` INT NOT NULL,
  `Produtos_idProduto` INT NOT NULL,
  PRIMARY KEY (`Fornecedores_idFornecedor`, `Produtos_idProduto`),
  INDEX `fk_Fornecedores_has_Produtos_Produtos1_idx` (`Produtos_idProduto` ASC) VISIBLE,
  INDEX `fk_Fornecedores_has_Produtos_Fornecedores1_idx` (`Fornecedores_idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedores_has_Produtos_Fornecedores1`
    FOREIGN KEY (`Fornecedores_idFornecedor`)
    REFERENCES `mydb`.`Fornecedores` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedores_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_idProduto`)
    REFERENCES `mydb`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT,
  `Local` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos no Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos no Estoque` (
  `Produtos_idProduto` INT NOT NULL AUTO_INCREMENT,
  `Estoque_idEstoque` INT NOT NULL,
  `Quantidade` INT NOT NULL DEFAULT 0,
  `Status` ENUM("Disponivel", "sem Estoque") NULL DEFAULT 'Disponivel',
  PRIMARY KEY (`Produtos_idProduto`, `Estoque_idEstoque`),
  INDEX `fk_Produtos_has_Estoque_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  INDEX `fk_Produtos_has_Estoque_Produtos1_idx` (`Produtos_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_has_Estoque_Produtos1`
    FOREIGN KEY (`Produtos_idProduto`)
    REFERENCES `mydb`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Itens do Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Itens do Pedido` (
  `Produtos_idProduto` INT NOT NULL,
  `Pedidos_idPedido` INT NOT NULL,
  `Quantidade` FLOAT(5,3) NOT NULL DEFAULT 0,
  `Valor do Item` FLOAT(14,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`Produtos_idProduto`, `Pedidos_idPedido`),
  INDEX `fk_Produtos_has_Pedidos_Pedidos1_idx` (`Pedidos_idPedido` ASC) VISIBLE,
  INDEX `fk_Produtos_has_Pedidos_Produtos1_idx` (`Produtos_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_has_Pedidos_Produtos1`
    FOREIGN KEY (`Produtos_idProduto`)
    REFERENCES `mydb`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_has_Pedidos_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedido`)
    REFERENCES `mydb`.`Pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Representante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Representante` (
  `idRepresentante` INT NOT NULL AUTO_INCREMENT,
  `Indentificação` CHAR(14) NOT NULL COMMENT 'Não sendo PessoaFísica TRUE então trata-se de CNPJ',
  `Razação Social` VARCHAR(45) NOT NULL,
  `Local` VARCHAR(255) NULL,
  `Nome de Fantasia` VARCHAR(45) NULL,
  `PessoaFísica` TINYINT NOT NULL,
  PRIMARY KEY (`idRepresentante`),
  UNIQUE INDEX `Razação Social_UNIQUE` (`Razação Social` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`Indentificação` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto por representante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto por representante` (
  `Produtos_idProduto` INT NOT NULL,
  `Representante_idRepresentante` INT NOT NULL,
  `Quantidade` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`Produtos_idProduto`, `Representante_idRepresentante`),
  INDEX `fk_Produtos_has_Representante_Representante1_idx` (`Representante_idRepresentante` ASC) VISIBLE,
  INDEX `fk_Produtos_has_Representante_Produtos1_idx` (`Produtos_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_has_Representante_Produtos1`
    FOREIGN KEY (`Produtos_idProduto`)
    REFERENCES `mydb`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_has_Representante_Representante1`
    FOREIGN KEY (`Representante_idRepresentante`)
    REFERENCES `mydb`.`Representante` (`idRepresentante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Forma de Pagamentos dos Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Forma de Pagamentos dos Pedidos` (
  `Forma de Pagamentos_idForma de Pagamento` INT NOT NULL,
  `Pedidos_idPedido` INT NOT NULL,
  PRIMARY KEY (`Forma de Pagamentos_idForma de Pagamento`, `Pedidos_idPedido`),
  INDEX `fk_Forma de Pagamentos_has_Pedidos_Pedidos1_idx` (`Pedidos_idPedido` ASC) VISIBLE,
  INDEX `fk_Forma de Pagamentos_has_Pedidos_Forma de Pagamentos1_idx` (`Forma de Pagamentos_idForma de Pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Forma de Pagamentos_has_Pedidos_Forma de Pagamentos1`
    FOREIGN KEY (`Forma de Pagamentos_idForma de Pagamento`)
    REFERENCES `mydb`.`Forma de Pagamentos` (`idForma de Pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Forma de Pagamentos_has_Pedidos_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedido`)
    REFERENCES `mydb`.`Pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cartão de crédito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cartão de crédito` (
  `idCartão de crédito` INT NOT NULL AUTO_INCREMENT,
  `Número` INT NOT NULL,
  `Titular` VARCHAR(45) NOT NULL,
  `Validade` DATE NOT NULL,
  `CVC` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Forma de Pagamentos_idForma de Pagamento` INT NOT NULL,
  PRIMARY KEY (`idCartão de crédito`, `Forma de Pagamentos_idForma de Pagamento`),
  INDEX `fk_Cartão de crédito_Forma de Pagamentos1_idx` (`Forma de Pagamentos_idForma de Pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Cartão de crédito_Forma de Pagamentos1`
    FOREIGN KEY (`Forma de Pagamentos_idForma de Pagamento`)
    REFERENCES `mydb`.`Forma de Pagamentos` (`idForma de Pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
