-- MySQL Script generated by MySQL Workbench
-- Mon Nov  7 16:19:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Payments` (
  `idPayment` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`idPayment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`PaymentsOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`PaymentsOrder` (
  `Payments_idPayments` INT NOT NULL,
  `Order_idOrder` INT NOT NULL,
  PRIMARY KEY (`Payments_idPayments`, `Order_idOrder`),
  INDEX `fk_PaymentsOrder_has_Order_Order1_idx` (`Order_idOrder` ASC) VISIBLE,
  INDEX `fk_PaymentsOrder_has_Order_PaymentsOrder1_idx` (`Payments_idPayments` ASC) INVISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `ecommerce`.`CreditCard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`CreditCard` (
  `idCreditCard` INT NOT NULL AUTO_INCREMENT,
  `Number` INT NOT NULL,
  `Titular` VARCHAR(45) NOT NULL,
  `Validity` DATE NOT NULL,
  `CVC` VARCHAR(45) NOT NULL,
  `Payments_idPayment` INT NOT NULL,
  PRIMARY KEY (`idCreditCard`, `Payments_idPayment`),
  INDEX `fk_CreditCard_Payments1_idx` (`Payments_idPayment` ASC) INVISIBLE,
  CONSTRAINT `fk_CreditCard_Payments1`
    FOREIGN KEY (`Payments_idPayment`)
    REFERENCES `ecommerce`.`Payments` (`idPayment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
